/* Dictionnaire anglais — INTERCEPTOR (by NeoZ)
 *
 * La cle est le texte francais tel qu il apparait dans le code. Une entree
 * absente laisse le texte francais s afficher : jamais de vide ni de cle brute.
 */
import { EN_MENUS } from './dict-en-menus.js';
import { EN_TOOLS } from './dict-en-tools.js';
import { EN_REGLAGES } from './dict-en-reglages.js';

export const EN = {
  /* ------------------------------ Navigation ----------------------------- */
  'Requetes': 'Requests',
  'Securite': 'Security',
  'Synthese': 'Summary',
  'Comparaison': 'Comparison',
  'Flux direct': 'Live streams',
  'Cookies': 'Cookies',
  'Navigation': 'Navigation',
  'Contexte': 'Context',
  'Diagnostic': 'Diagnostics',
  'Regles': 'Rules',
  'Reglages': 'Settings',
  'Tutoriel': 'Tutorial',
  'Aide': 'Help',
  'Trafic': 'Traffic',
  'Journaux': 'Logs',
  'Systeme': 'System',
  'Apprendre': 'Learn',

  /* -------------------------------- En-tete ------------------------------ */
  'Capture': 'Capturing',
  'En pause': 'Paused',
  'Exporter': 'Export',
  'Actions': 'Actions',
  'Vider': 'Clear',
  'Onglet actif': 'Active tab',
  'Tout Firefox': 'All of Firefox',
  'Onglets ouverts': 'Open tabs',
  'corps': 'bodies',
  'Perimetre observe': 'Observed scope',
  'Vider toute la capture': 'Clear the whole capture',
  'Aide sur la recherche': 'Search help',
  'Filtres enregistres': 'Saved filters',
  'Recherches recentes': 'Recent searches',
  'Enregistrer le filtre courant': 'Save current filter',
  'Oublier le dernier filtre enregistre': 'Forget last saved filter',
  'Aucun filtre enregistre': 'No saved filter',

  /* ----------------------------- Barre d outils -------------------------- */
  'Colonnes': 'Columns',
  'Tri': 'Sort',
  'Suivre': 'Follow',
  'Fige': 'Frozen',
  'Tout selectionner': 'Select all',
  'Deselectionner': 'Clear selection',
  'Supprimer': 'Delete',
  'Comparer': 'Compare',
  'affichees': 'shown',
  'sur': 'of',
  'selectionnees': 'selected',

  /* -------------------------------- Facettes ----------------------------- */
  'API': 'API',
  'Pages': 'Pages',
  'Ressources': 'Assets',
  'Flux': 'Streams',
  'Erreurs': 'Errors',
  'Alertes': 'Alerts',
  'Tiers': 'Third-party',
  'Avec corps': 'With body',
  'Epinglees': 'Pinned',
  'Lentes': 'Slow',
  'Sans reseau': 'No network',
  'Pistage Firefox': 'Firefox tracking',
  'Importees': 'Imported',

  /* -------------------------------- Colonnes ----------------------------- */
  'Heure': 'Time',
  'Meth.': 'Method',
  'Statut': 'Status',
  'Etat': 'State',
  'Proto': 'Proto',
  'Schema': 'Scheme',
  'Type': 'Type',
  'Hote': 'Host',
  'Chemin': 'Path',
  'URL complete': 'Full URL',
  'Origine': 'Initiator',
  'MIME': 'MIME',
  'Taille': 'Size',
  'Transfere': 'Transferred',
  'Envoye': 'Sent',
  'Duree': 'Duration',
  'Serveur': 'Server',
  'Pistage': 'Tracking',
  'Sur le fil': 'On the wire',
  'TLS': 'TLS',
  'Couches': 'Layers',
  'Marqueurs': 'Tags',
  'Redir.': 'Redir.',
  'Trames': 'Frames',
  'SSE': 'SSE',
  'Fusions': 'Merges',
  'Onglet': 'Tab',
  'Cadre': 'Frame',
  'Cascade': 'Waterfall',
  'Epingle': 'Pinned',
  'Niveau de risque': 'Risk level',

  /* --------------------------- Onglets du detail ------------------------- */
  'En-tetes': 'Headers',
  'Requete': 'Request',
  'Reponse': 'Response',
  'Chronologie': 'Timing',
  'Pile JS': 'JS stack',
  'Rejouer': 'Replay',
  'Brut': 'Raw',
  'Ouvrir': 'Open',
  'Bloquer': 'Block',
  'Copier': 'Copy',
  'Fermer le detail': 'Close detail',
  'Ligne precedente': 'Previous row',
  'Ligne suivante': 'Next row',
  'Epingler': 'Pin',

  /* -------------------------------- Etats -------------------------------- */
  'Aucune requete': 'No requests',
  'Aucune alerte': 'No alerts',
  'Aucun flux': 'No streams',
  'Journal vide': 'Empty log',
  'Aucune regle': 'No rules',
  'Rien a resumer': 'Nothing to summarise',
  'Selectionnez deux lignes': 'Select two rows',
  'En attente du noyau': 'Waiting for the core',

  /* ------------------------------- Messages ------------------------------ */
  'Capture reprise': 'Capture resumed',
  'Capture en pause': 'Capture paused',
  'Capture videe': 'Capture cleared',
  'Copie dans le presse-papiers': 'Copied to clipboard',
  'Copie refusee par le navigateur': 'Copy refused by the browser',
  'Rien a exporter': 'Nothing to export',
  'Aucune ligne': 'No rows',
  'Preparation de l export…': 'Preparing export…',
  'Analyse en cours…': 'Analysing…',
  'Gardez au moins une colonne': 'Keep at least one column',
  'Selectionnez exactement deux lignes avec Ctrl+clic': 'Select exactly two rows with Ctrl+click',
  'Selectionnez d abord des lignes (Ctrl+clic)': 'Select rows first (Ctrl+click)',
  'Ecrivez d abord un filtre a enregistrer': 'Type a filter to save first',
  'Filtre enregistre — bouton ★ a cote de la recherche': 'Filter saved — ★ button next to the search box',
  'Ce filtre est deja enregistre': 'This filter is already saved',
  'Dernier filtre enregistre oublie': 'Last saved filter forgotten',
  'Stockage sur disque vide': 'On-disk storage emptied',
  'Redemarrage de l extension…': 'Restarting the extension…',
  'Regle deja presente': 'Rule already present',
  'Ligne supprimee': 'Row deleted',
  'URL copiee': 'URL copied',
  'Commande cURL copiee': 'cURL command copied',
  'Enregistrement copie': 'Record copied',
  'Hote inconnu': 'Unknown host',
  'Ouverture impossible': 'Cannot open',
  'Seules les URL http et https sont ouvrables': 'Only http and https URLs can be opened',
  'Noyau injoignable — rechargez l extension': 'Core unreachable — reload the extension',
  'Lien avec le noyau interrompu — rechargez la page': 'Link with the core lost — reload the page',
  'Progression remise a zero': 'Progress reset',
  'Tutoriel marque comme termine': 'Tutorial marked as complete',
  'Tutoriel termine — bonne chasse.': 'Tutorial complete — happy hunting.',

  /* ------------------------------- Reglages ------------------------------ */
  'Interface': 'Interface',
  'Couches de capture': 'Capture layers',
  'Corps de requete et de reponse': 'Request and response bodies',
  'Correlation anti-doublon': 'Duplicate-free correlation',
  'Stockage': 'Storage',
  'Filtres d ingestion': 'Ingestion filters',
  'Analyse automatique': 'Automatic analysis',
  'Interception active': 'Active interception',
  'Profils rapides': 'Quick profiles',
  'Langue': 'Language',
  'Theme': 'Theme',
  'Sombre': 'Dark',
  'Clair': 'Light',
  'Suivre le systeme': 'Follow the system',
  'Francais': 'French',
  'Anglais': 'English',
  'Mode simple': 'Simple mode',
  'Densite du tableau': 'Table density',
  'Confortable': 'Comfortable',
  'Compacte': 'Compact',
  'Maximum': 'Maximum',
  'Equilibre': 'Balanced',
  'Leger': 'Light',
  'Observation discrete': 'Quiet observation',
  'Restaurer les reglages par defaut': 'Restore default settings',
  'Confirmer la remise a zero ?': 'Confirm reset?',
  'Reglages par defaut restaures': 'Default settings restored',
  'Importer': 'Import',
  'Importer un fichier HAR': 'Import a HAR file',
  'Importer une session JSON': 'Import a JSON session',
  'Exporter dans un fichier': 'Export to a file',
  'Copier les reglages': 'Copy settings',
  'Relancer le tutoriel': 'Restart the tutorial',
  'Colonnes par defaut': 'Default columns',
  'Actualiser': 'Refresh',
  'Lancer le test': 'Run the test',
  'Compter les enregistrements': 'Count records',
  'Purger le stockage': 'Purge storage',
  'Confirmer la purge ?': 'Confirm purge?',
  'Tout reanalyser': 'Re-analyse everything',
  'Exporter le rapport': 'Export the report',
  'Copier la synthese': 'Copy the summary',
  'Retirer les filtres': 'Clear filters',
  'Ajouter une regle': 'Add a rule',
  'Mode JSON': 'JSON mode',
  'Editeur visuel': 'Visual editor',
  'Copier les regles': 'Copy the rules',
  'Tout supprimer': 'Delete everything',
  'Confirmer ?': 'Confirm?',
  'Dupliquer': 'Duplicate',
  'Raccourcis clavier': 'Keyboard shortcuts',
  'Fermer': 'Close',


  /* --------------------- Libelles des reglages --------------------------- */
  'Format de l heure': 'Time format',
  'Heure locale': 'Local time',
  'Temps ecoule': 'Elapsed time',
  'ISO 8601': 'ISO 8601',
  'Suivre le flux par defaut': 'Follow the flow by default',
  'Perimetre par defaut': 'Default scope',
  'Replier les longues lignes des corps': 'Wrap long body lines',
  'Mettre en forme le JSON automatiquement': 'Format JSON automatically',
  'Clic sur l icone': 'Clicking the icon',
  'Ouvre la fenetre compacte': 'Opens the compact window',
  'Ouvre la console complete': 'Opens the full console',
  'Compteur sur l icone': 'Icon counter',
  'Nombre de requetes': 'Number of requests',
  'Nombre d alertes': 'Number of alerts',
  'Aucun': 'None',
  'Notification bureau sur alerte critique': 'Desktop notification on critical alert',
  'Proposer le tutoriel a l installation': 'Offer the tutorial on install',
  'Contraste renforce': 'Higher contrast',
  'Taille du texte des donnees (%)': 'Data text size (%)',
  'Vider un onglet a chaque navigation': 'Clear a tab on each navigation',
  'Couche webRequest': 'webRequest layer',
  'Sondes du contexte page': 'Page-context probes',
  'Trames WebSocket': 'WebSocket frames',
  'Server-Sent Events': 'Server-Sent Events',
  'PerformanceObserver': 'PerformanceObserver',
  'Piles d appel JavaScript': 'JavaScript call stacks',
  'WebRTC': 'WebRTC',
  'Workers et Service Workers': 'Workers and Service Workers',
  'Cookies poses en JavaScript': 'Cookies set from JavaScript',
  'WebTransport (HTTP/3)': 'WebTransport (HTTP/3)',
  'Mesures de perception de page': 'Page perception metrics',
  'Mutations de cookies': 'Cookie changes',
  'TLS et certificats': 'TLS and certificates',
  'Resolution DNS': 'DNS resolution',
  'Couche proxy (avance)': 'Proxy layer (advanced)',
  'Corps envoyes': 'Sent bodies',
  'Corps recus': 'Received bodies',
  'Conserver le binaire': 'Keep binary data',
  'Limite par corps envoye (octets)': 'Limit per sent body (bytes)',
  'Limite par corps recu (octets)': 'Limit per received body (bytes)',
  'Limite du binaire conserve (octets)': 'Limit of binary kept (bytes)',
  'Limite par trame ou message (octets)': 'Limit per frame or message (bytes)',
  'Trames conservees par socket': 'Frames kept per socket',
  'Messages SSE conserves par flux': 'SSE messages kept per stream',
  'Types sans capture de corps': 'Types with no body capture',
  'Correlation active': 'Correlation active',
  'Fenetre de correlation (ms)': 'Correlation window (ms)',
  'Periode de verification (ms)': 'Sweep period (ms)',
  'Requetes conservees en memoire': 'Requests kept in memory',
  'Persistance sur disque': 'On-disk persistence',
  'Requetes rechargees au demarrage': 'Requests reloaded at startup',
  'Ignorer les requetes de l extension': 'Ignore the extension own requests',
  'Types de ressource ignores': 'Ignored resource types',
  'Ignorer les URL correspondant a': 'Ignore URLs matching',
  'Ne capturer que les URL correspondant a': 'Capture only URLs matching',
  'Analyse active': 'Analysis active',
  'Cles, jetons et identifiants': 'Keys, tokens and credentials',
  'Donnees personnelles (e-mail, carte bancaire, IBAN)': 'Personal data (e-mail, payment card, IBAN)',
  'Transport : HTTP en clair, TLS, certificats': 'Transport: cleartext HTTP, TLS, certificates',
  'Entetes de securite et CORS': 'Security headers and CORS',
  'Cookies de session mal proteges': 'Poorly protected session cookies',
  'Pisteurs et telemetrie': 'Trackers and telemetry',
  'Masquer les valeurs sensibles': 'Mask sensitive values',
  'Domaines de pistage supplementaires': 'Extra tracking domains',
  'Motifs de secret personnels': 'Custom secret patterns',
  'Moteur de regles': 'Rules engine',
  'Autoriser le rejeu de requete': 'Allow request replay',
  'Colonnes du tableau': 'Table columns',
  'Sauvegarde des reglages': 'Settings backup',
  'Remise a zero': 'Reset',

  /* ----------------------- Titres de sections ---------------------------- */
  'Identite': 'Identity',
  'Reseau': 'Network',
  'Contexte JavaScript': 'JavaScript context',
  'Authentification demandee': 'Authentication requested',
  'Proxy': 'Proxy',
  'Regles appliquees': 'Applied rules',
  'Rejeux': 'Replays',
  'Parametres de l URL': 'URL parameters',
  'Entetes envoyees': 'Sent headers',
  'Entetes recues': 'Received headers',
  'Corps envoye': 'Sent body',
  'Corps recu': 'Received body',
  'Champs de formulaire': 'Form fields',
  'Apercu hexadecimal': 'Hex preview',
  'Base64': 'Base64',
  'Set-Cookie': 'Set-Cookie',
  'Mutations observees': 'Observed changes',
  'Cookies du domaine': 'Cookies for this domain',
  'Voir les cookies du domaine': 'Show cookies for this domain',
  'Session TLS': 'TLS session',
  'Chaine de certificats': 'Certificate chain',
  'Certificat du serveur': 'Server certificate',
  'Analyse': 'Analysis',
  'WebSocket': 'WebSocket',
  'Messages': 'Messages',
  'Chronometrage reseau': 'Network timing',
  'Server-Timing': 'Server-Timing',
  'Chaine de redirection': 'Redirect chain',
  'Evenements observes': 'Observed events',
  'Pile d appel JavaScript': 'JavaScript call stack',
  'Enregistrement complet': 'Complete record',
  'Rejouer la requete': 'Replay the request',
  'Resultat du rejeu': 'Replay result',
  'Rejeux precedents': 'Previous replays',
  'Alertes detectees': 'Alerts found',
  'Detail': 'Detail',
  'Synthese du perimetre': 'Scope summary',
  'Statuts': 'Statuses',
  'Types de ressource': 'Resource types',
  'Protocoles observes': 'Observed protocols',
  'Domaines par volume recu': 'Domains by received volume',
  'Domaines par nombre de requetes': 'Domains by request count',
  'Types de contenu': 'Content types',
  'Marqueurs de l analyse': 'Analysis tags',
  'Requetes dans le temps': 'Requests over time',
  'Requetes les plus lentes': 'Slowest requests',
  'Reponses les plus lourdes': 'Heaviest responses',
  'Requetes les plus signalees': 'Most flagged requests',
  'Flux ouverts et fermes': 'Open and closed streams',
  'Journal des cookies': 'Cookie log',
  'Journal de navigation': 'Navigation log',
  'Journal de contexte': 'Context log',
  'Extension': 'Extension',
  'Anti-doublon': 'Duplicate control',
  'Corps de reponse': 'Response bodies',
  'Sondes du monde page': 'Page-world probes',
  'Etat des couches': 'Layer status',
  'Couches complementaires': 'Additional layers',
  'Verification de couverture': 'Coverage test',
  'Stockage sur disque': 'On-disk storage',
  'Comparaison de deux requetes': 'Comparing two requests',
  'Ecarts mesures': 'Measured differences',
  'Verification': 'Check',
  'Reponse simulee': 'Mocked response',
  'Entetes de requete': 'Request headers',
  'Entetes de reponse': 'Response headers',

  /* -------------------------------- Divers ------------------------------- */
  'Critiques': 'Critical',
  'Elevees': 'High',
  'Moyennes': 'Medium',
  'Faibles': 'Low',
  'Information': 'Info',
  'requetes': 'requests',
  'domaines': 'domains',
  'recu': 'received',
  'envoye': 'sent',
  'duree mediane': 'median duration',
  'en erreur': 'failed',
  'alertes': 'alerts',
  'tierces': 'third-party',
  'chiffrees': 'encrypted',
  'depuis le cache': 'from cache',
  'trames et messages': 'frames and messages',
  'cookies poses': 'cookies set',
  'enregistrees': 'recorded',
  'en memoire': 'in memory',
  'terminees': 'completed',
  'fusions': 'merges',
  'entrant': 'inbound',
  'sortant': 'outbound',
  'req/s': 'req/s',

  /* Menus Exporter, Copier et generateurs de code : voir dict-en-menus.js.
     Boite a outils, Cible et Diagnostic interne : voir dict-en-tools.js. */
  ...EN_MENUS,
  ...EN_TOOLS,
  ...EN_REGLAGES
};
